// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ja'

export type Locales =
	| 'en'
	| 'it'
	| 'ja'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * 自​分​の​路​を​進​む​姿​を​、​風​が​後​押​し​し​て​い​る​様​子​を​表​現​し​た​作​品
	 */
	hero: string
	aboutme: {
		/**
		 * 渡​邉​麻​美
		 */
		name: string
		/**
		 * <​s​p​a​n​ ​l​a​n​g​=​"​e​n​"​>​A​b​o​u​t​ ​M​e​<​/​s​p​a​n​>
		 */
		header: string
		/**
		 * <​s​t​r​o​n​g​ ​s​t​y​l​e​=​'​f​o​n​t​-​s​i​z​e​:​v​a​r​(​-​-​t​e​x​t​-​m​d​)​'​>​イ​ラ​ス​ト​レ​ー​タ​ー​／​画​家​<​/​s​t​r​o​n​g​>​
	​宇​宙​・​自​然​・​動​物​を​テ​ー​マ​に​、​ア​ナ​ロ​グ​と​デ​ジ​タ​ル​の​両​方​で​作​品​を​制​作​し​て​い​ま​す​。​
	​星​の​瞬​き​や​空​や​海​、​自​然​の​静​寂​、​生​き​物​た​ち​の​存​在​感​
	​目​に​見​え​る​も​の​の​奥​に​あ​る​世​界​を​描​く​こ​と​で​、​見​る​人​の​心​に​豊​か​に​広​が​る​、​物​語​性​の​あ​る​一​枚​を​目​指​し​て​い​ま​す​。
		 */
		description: string
	}
	ui: {
		screenreader: {
			/**
			 * 言​語​を​変​更
			 */
			change_language: string
			/**
			 * メ​ニ​ュ​ー​を​開​く
			 */
			open_menu: string
			/**
			 * メ​ニ​ュ​ー​を​閉​じ​る
			 */
			close_menu: string
			/**
			 * イ​ン​ス​タ​グ​ラ​ム
			 */
			instagram: string
			/**
			 * テ​レ​グ​ラ​ム
			 */
			telegram: string
		}
		cta: {
			/**
			 * オ​ー​ダ​ー​イ​ラ​ス​ト​を​ご​希​望​で​す​か
			 */
			looking_for_commission: string
			/**
			 * メ​ッ​セ​ー​ジ​を​送​る
			 */
			send_me_message: string
		}
	}
	seo: {
		/**
		 * イ​ラ​ス​ト​レ​ー​タ​ー
		 */
		illustrator: string
		/**
		 * 女​性
		 */
		gender: string
		/**
		 * 日​本
		 */
		japan: string
		artMedium: {
			/**
			 * フ​ァ​イ​ン​ラ​イ​ナ​ー​／​デ​ジ​タ​ル​ペ​イ​ン​テ​ィ​ン​グ
			 */
			liner_digital: string
			/**
			 * フ​ァ​イ​ン​ラ​イ​ナ​ー​／​色​鉛​筆
			 */
			liner_color: string
			/**
			 * グ​ラ​フ​ァ​イ​ト​鉛​筆​／​ア​ク​リ​ル​絵​具
			 */
			pencil_acrylic: string
			/**
			 * グ​ラ​フ​ァ​イ​ト​鉛​筆​／​色​鉛​筆
			 */
			pencil_color: string
		}
		material: {
			/**
			 * イ​ン​ク
			 */
			ink: string
			/**
			 * デ​ジ​タ​ル​メ​デ​ィ​ア
			 */
			digital: string
			/**
			 * 色​鉛​筆
			 */
			color_pencil: string
			/**
			 * グ​ラ​フ​ァ​イ​ト
			 */
			graphite: string
			/**
			 * ア​ク​リ​ル
			 */
			acrylic: string
			/**
			 * 紙
			 */
			paper: string
		}
		homepage: {
			/**
			 * 渡​邉​麻​美​ ​–​ ​現​代​日​本​の​ア​ー​テ​ィ​ス​ト
			 */
			title: string
			/**
			 * 現​代​日​本​の​ア​ー​テ​ィ​ス​ト​・​渡​邉​麻​美​の​公​式​ポ​ー​ト​フ​ォ​リ​オ​。​幻​想​的​な​世​界​観​、​創​作​の​歩​み​、​そ​し​て​厳​選​さ​れ​た​イ​ラ​ス​ト​や​絵​画​の​ギ​ャ​ラ​リ​ー​を​ご​覧​い​た​だ​け​ま​す​。
			 */
			description: string
		}
		works: {
			Gallery_1_Fantastic_World: {
				/**
				 * 幻​想​的​な​世​界​ ​–​ ​渡​邉​麻​美​の​作​品
				 */
				title: string
				/**
				 * 「​幻​想​的​な​世​界​」​は​、​渡​邉​麻​美​に​よ​る​想​像​力​豊​か​で​夢​の​よ​う​な​イ​ラ​ス​ト​を​集​め​た​ギ​ャ​ラ​リ​ー​で​す​。​神​話​的​な​要​素​や​宇​宙​的​視​点​、​遊​び​心​あ​る​シ​ュ​ー​ル​な​表​現​が​、​物​語​性​あ​ふ​れ​る​世​界​を​描​き​出​し​ま​す​。
				 */
				description: string
			}
			Gallery_2_Nature_Inner_World: {
				/**
				 * 自​然​と​内​な​る​世​界​ ​–​ ​渡​邉​麻​美​の​作​品
				 */
				title: string
				/**
				 * 「​自​然​と​内​な​る​世​界​」​で​は​、​自​然​の​モ​チ​ー​フ​と​心​の​象​徴​を​組​み​合​わ​せ​た​渡​邉​麻​美​の​作​品​を​ご​紹​介​し​ま​す​。​動​物​、​民​話​、​内​省​的​な​情​景​が​、​記​憶​や​想​像​、​心​の​風​景​を​優​し​く​描​き​出​し​ま​す​。
				 */
				description: string
			}
			POP_Illustrations: {
				/**
				 * ポ​ッ​プ​イ​ラ​ス​ト​ ​–​ ​渡​邉​麻​美​の​作​品
				 */
				title: string
				/**
				 * 「​ポ​ッ​プ​イ​ラ​ス​ト​」​は​、​色​彩​豊​か​で​キ​ャ​ラ​ク​タ​ー​性​あ​ふ​れ​る​作​品​を​集​め​た​ギ​ャ​ラ​リ​ー​で​す​。​遊​び​心​と​ユ​ー​モ​ア​に​満​ち​た​イ​ラ​ス​ト​が​、​日​常​の​喜​び​や​想​像​の​世​界​を​軽​や​か​に​表​現​し​ま​す​。
				 */
				description: string
			}
			Nigaoe_Works: {
				/**
				 * 似​顔​絵​ワ​ー​ク​ス​ ​–​ ​渡​邉​麻​美​の​イ​ラ​ス​ト
				 */
				title: string
				/**
				 * 「​似​顔​絵​ワ​ー​ク​ス​」​は​、​渡​邉​麻​美​に​よ​る​パ​ー​ソ​ナ​ル​な​似​顔​絵​作​品​の​コ​レ​ク​シ​ョ​ン​で​す​。​家​族​の​肖​像​、​ベ​イ​ビ​ー​ポ​ス​タ​ー​、​記​念​日​の​イ​ラ​ス​ト​な​ど​、​大​切​な​瞬​間​や​絆​を​温​か​く​描​き​出​し​ま​す​。
				 */
				description: string
			}
			Others: {
				/**
				 * そ​の​他​の​作​品​ ​–​ ​渡​邉​麻​美​の​イ​ラ​ス​ト
				 */
				title: string
				/**
				 * 「​そ​の​他​の​作​品​」​は​、​渡​邉​麻​美​に​よ​る​小​品​や​表​現​豊​か​な​イ​ラ​ス​ト​を​集​め​た​ギ​ャ​ラ​リ​ー​で​す​。​シ​ン​プ​ル​で​象​徴​的​、​そ​し​て​心​に​寄​り​添​う​作​品​を​ご​覧​い​た​だ​け​ま​す​。
				 */
				description: string
			}
		}
	}
	works: {
		Gallery_1_Fantastic_World: {
			/**
			 * ギ​ャ​ラ​リ​ー​1​：​<​b​r​>​幻​想​的​な​世​界
			 */
			title: string
			descriptions: {
				/**
				 * 月​光​花​の​よ​う​に​儚​く​も​美​し​く​咲​く​人​々​が​集​ま​る​夜​の​世​界
				 */
				moonFlower: string
				/**
				 * 卵​の​中​か​ら​生​ま​れ​る​も​の​は​何​？​そ​ん​な​期​待​が​入​り​混​じ​る​中​。​さ​あ​シ​ョ​ー​が​始​ま​る​よ​！
				 */
				theStage: string
				/**
				 * 北​極​星​か​ら​見​る​地​球​の​歴​史​は​き​っ​と​ま​だ​短​い​の​だ​ろ​う
				 */
				polaris: string
				/**
				 * 星​の​ベ​ッ​ド​に​横​た​わ​り​ゆ​っ​く​り​と​し​た​時​間​を​楽​し​む​兄​妹​ラ​イ​オ​ン
				 */
				relaxingTime: string
				/**
				 * お​揃​い​の​バ​ッ​ジ​を​つ​け​た​熱​狂​的​フ​ァ​ン​達​は​氷​を​溶​か​す​く​ら​い​の​盛​り​上​が​り​で​す​！
				 */
				passionateAudience: string
				/**
				 * 現​代​社​会​に​吹​き​荒​れ​る​風​は​風​神​と​雷​神​が​も​た​ら​す​パ​ワ​ー​な​の​か​も​し​れ​な​い​と​い​う​発​想​か​ら​生​み​出​さ​れ​た​イ​ラ​ス​ト
				 */
				fujinLajin: string
				/**
				 * 辰​年​を​イ​メ​ー​ジ​し​た​お​正​月​の​お​祝​い​カ​ー​ド
				 */
				newYear: string
			}
		}
		Gallery_2_Nature_Inner_World: {
			/**
			 * ギ​ャ​ラ​リ​ー​2​：​<​b​r​>​自​然​と​内​な​る​世​界
			 */
			title: string
			descriptions: {
				/**
				 * 白​熊​の​毛​は​白​く​見​え​る​け​ど​、​か​き​氷​の​氷​と​同​じ​く​透​明​で​す
				 */
				fluffyShavedIce: string
				/**
				 * 深​海​は​き​っ​と​見​え​な​い​色​や​形​に​溢​れ​て​い​る​世​界
				 */
				deepInTheSea: string
				/**
				 * 僕​の​体​の​8​0​%​は​海​か​ら​で​き​て​い​る​ん​だ​よ​！
				 */
				iWannaSea: string
				/**
				 * 未​知​の​生​き​物​は​魅​力​的​な​デ​ザ​イ​ン​で​着​飾​っ​て​い​る
				 */
				sakana: string
				/**
				 * 小​さ​な​町​に​突​然​降​っ​た​大​雪​で​現​れ​た​大​き​な​雪​だ​る​ま
				 */
				busStop: string
				/**
				 * ウ​サ​ギ​の​家​族​が​お​に​ぎ​り​を​持​っ​て​ピ​ク​ニ​ッ​ク​に​出​か​け​た​よ
				 */
				picnic: string
				/**
				 * 私​は​観​賞​用​で​す​。​食​べ​ら​れ​ま​せ​ん​。
				 */
				nishikigoi: string
				/**
				 * お​ば​あ​ち​ゃ​ん​の​部​屋​に​は​面​白​い​も​の​が​た​く​さ​ん​あ​っ​て​飽​き​な​い​な
				 */
				playStaringContest: string
				/**
				 * 目​指​す​は​場​所​は​ウ​サ​ギ​の​い​る​月
				 */
				tripAdventure: string
				/**
				 * か​ぐ​や​姫​の​住​む​世​界
				 */
				princessKaguya: string
				/**
				 * 笑​顔​弾​け​る​夏​祭​り​へ​よ​う​こ​そ
				 */
				maturi: string
				/**
				 * 「​あ​り​が​と​う​」​の​気​持​ち​を​マ​ト​リ​ョ​ー​シ​カ​に​込​め​て
				 */
				arigatou: string
				/**
				 * 他​人​は​自​分​を​写​す​鏡​の​よ​う​な​も​の
				 */
				hearts: string
				/**
				 * 希​望​と​不​安​を​バ​ル​ー​ン​に​込​め​て​飛​び​立​つ​決​心​を​し​た​少​女
				 */
				theFirstLightDawn: string
			}
		}
		POP_Illustrations: {
			/**
			 * ポ​ッ​プ​イ​ラ​ス​ト
			 */
			title: string
			descriptions: {
				/**
				 * 空​飛​ぶ​宇​宙​ク​ジ​ラ​１
				 */
				wheel: string
				/**
				 * 空​飛​ぶ​宇​宙​ク​ジ​ラ​２
				 */
				wheel2: string
				/**
				 * 古​典​模​様​を​取​り​入​れ​、​古​さ​と​新​し​さ​を​交​え​た​惑​星​の​イ​ラ​ス​ト
				 */
				planets: string
				/**
				 * カ​ラ​フ​ル​な​テ​ン​ト​の​中​で​魅​惑​的​な​パ​フ​ォ​ー​マ​ン​ス​に​夢​中
				 */
				circus: string
				/**
				 * 愛​す​る​人​達​へ​の​想​い​を​キ​ラ​キ​ラ​の​ツ​リ​ー​の​飾​り​に​込​め​て
				 */
				bigTree: string
				/**
				 * 楽​し​い​音​楽​と​共​に​特​別​な​舟​で​旅​を​し​よ​う​！
				 */
				boat: string
				/**
				 * 大​き​な​ヨ​ー​ヨ​ー​は​ま​る​で​生​き​物​み​た​い​に​バ​ウ​ン​ド​す​る​か​ら​大​変​だ
				 */
				twins: string
				/**
				 * 大​根​役​者​は​実​は​い​い​味​出​し​て​る​愛​さ​れ​キ​ャ​ラ​ク​タ​ー
				 */
				funnyGuy: string
				/**
				 * 3​人​の​魔​女​は​お​洒​落​を​し​て​お​出​か​け​の​準​備​中
				 */
				pumpinkHouse: string
				/**
				 * 立​派​な​レ​ン​コ​ン​の​車​輪​が​つ​い​た​お​城​は​彼​女​の​お​気​に​入​り
				 */
				lotusRootCastle: string
				/**
				 * 話​を​聞​く​よ​と​近​寄​っ​て​く​る​可​愛​ら​し​い​お​友​達
				 */
				threeHares: string
				/**
				 * 彼​の​帽​子​は​カ​ラ​フ​ル​で​、​雨​に​も​負​け​な​い​大​人​気​の​帽​子​で​す
				 */
				lovelyHat: string
				/**
				 * 動​物​達​の​生​き​生​き​と​し​た​姿​は​自​然​の​中​で​し​か​見​る​こ​と​は​で​き​な​い
				 */
				zoo: string
				/**
				 * 大​好​き​な​ど​ん​ぐ​り​に​囲​ま​れ​て​し​あ​わ​せ​な​リ​ス
				 */
				nutsToYou: string
				/**
				 * 陣​取​り​合​戦​し​て​い​た​ら​タ​ワ​ー​に​な​っ​て​し​ま​っ​た​猫​の​兄​弟
				 */
				kittyTower: string
				/**
				 * 今​夜​は​チ​ー​ズ​パ​ー​テ​ィ​ー​を​開​催​し​ま​す
				 */
				letsStartTheParty: string
				/**
				 * 夜​空​に​浮​か​ぶ​星​た​ち​は​ま​る​で​サ​メ​の​よ​う​に​素​早​く​移​動​し​て​い​る
				 */
				swimming: string
				/**
				 * 可​愛​ら​し​い​ラ​ン​タ​ン​達​は​ど​ん​ど​ん​上​昇​し​雲​の​上​ま​で​た​ど​り​着​き​ま​し​た
				 */
				animalsLantern: string
				/**
				 * お​餅​の​よ​う​な​み​た​め​彼​ら​は​お​汁​粉​の​お​風​呂​で​溶​け​て​し​ま​い​そ​う
				 */
				oshiruko: string
			}
		}
		Nigaoe_Works: {
			/**
			 * 似​顔​絵​ワ​ー​ク​ス
			 */
			title: string
			descriptions: {
				/**
				 * 日​本​の​伝​統​的​な​吉​報​模​様​を​背​景​に​家​族​の​幸​せ​を​願​い​描​き​ま​し​た
				 */
				family1: string
				/**
				 * 結​婚​記​念​日​に​奥​様​か​ら​の​サ​プ​ラ​イ​ズ​似​顔​絵
				 */
				family2: string
				/**
				 * 大​切​な​家​族​を​迎​え​ら​れ​た​記​念​に​ペ​ッ​ト​の​名​前​「​さ​く​ら​」​を​背​景​に​描​い​て​い​ま​す
				 */
				pet: string
				/**
				 * 女​の​子​の​誕​生​日​メ​ッ​セ​ー​ジ​付​き​ベ​イ​ビ​ー​ポ​ス​タ​ー
				 */
				baby1: string
				/**
				 * 男​の​子​の​誕​生​日​メ​ッ​セ​ー​ジ​付​き​ベ​イ​ビ​ー​ポ​ス​タ​ー
				 */
				baby2: string
				/**
				 * 女​の​子​の​メ​ッ​セ​ー​ジ​付​き​似​顔​絵
				 */
				girl: string
				/**
				 * 男​の​子​の​メ​ッ​セ​ー​ジ​付​き​似​顔​絵
				 */
				boy: string
			}
		}
		Others: {
			/**
			 * そ​の​他​の​作​品
			 */
			title: string
			descriptions: {
				/**
				 * 女​の​子
				 */
				girl: string
				/**
				 * 年​賀​状
				 */
				newYearCard: string
				/**
				 * 笑​顔
				 */
				smile: string
			}
		}
	}
}

export type TranslationFunctions = {
	/**
	 * 自分の路を進む姿を、風が後押ししている様子を表現した作品
	 */
	hero: () => LocalizedString
	aboutme: {
		/**
		 * 渡邉麻美
		 */
		name: () => LocalizedString
		/**
		 * <span lang="en">About Me</span>
		 */
		header: () => LocalizedString
		/**
		 * <strong style='font-size:var(--text-md)'>イラストレーター／画家</strong>
	宇宙・自然・動物をテーマに、アナログとデジタルの両方で作品を制作しています。
	星の瞬きや空や海、自然の静寂、生き物たちの存在感
	目に見えるものの奥にある世界を描くことで、見る人の心に豊かに広がる、物語性のある一枚を目指しています。
		 */
		description: () => LocalizedString
	}
	ui: {
		screenreader: {
			/**
			 * 言語を変更
			 */
			change_language: () => LocalizedString
			/**
			 * メニューを開く
			 */
			open_menu: () => LocalizedString
			/**
			 * メニューを閉じる
			 */
			close_menu: () => LocalizedString
			/**
			 * インスタグラム
			 */
			instagram: () => LocalizedString
			/**
			 * テレグラム
			 */
			telegram: () => LocalizedString
		}
		cta: {
			/**
			 * オーダーイラストをご希望ですか
			 */
			looking_for_commission: () => LocalizedString
			/**
			 * メッセージを送る
			 */
			send_me_message: () => LocalizedString
		}
	}
	seo: {
		/**
		 * イラストレーター
		 */
		illustrator: () => LocalizedString
		/**
		 * 女性
		 */
		gender: () => LocalizedString
		/**
		 * 日本
		 */
		japan: () => LocalizedString
		artMedium: {
			/**
			 * ファインライナー／デジタルペインティング
			 */
			liner_digital: () => LocalizedString
			/**
			 * ファインライナー／色鉛筆
			 */
			liner_color: () => LocalizedString
			/**
			 * グラファイト鉛筆／アクリル絵具
			 */
			pencil_acrylic: () => LocalizedString
			/**
			 * グラファイト鉛筆／色鉛筆
			 */
			pencil_color: () => LocalizedString
		}
		material: {
			/**
			 * インク
			 */
			ink: () => LocalizedString
			/**
			 * デジタルメディア
			 */
			digital: () => LocalizedString
			/**
			 * 色鉛筆
			 */
			color_pencil: () => LocalizedString
			/**
			 * グラファイト
			 */
			graphite: () => LocalizedString
			/**
			 * アクリル
			 */
			acrylic: () => LocalizedString
			/**
			 * 紙
			 */
			paper: () => LocalizedString
		}
		homepage: {
			/**
			 * 渡邉麻美 – 現代日本のアーティスト
			 */
			title: () => LocalizedString
			/**
			 * 現代日本のアーティスト・渡邉麻美の公式ポートフォリオ。幻想的な世界観、創作の歩み、そして厳選されたイラストや絵画のギャラリーをご覧いただけます。
			 */
			description: () => LocalizedString
		}
		works: {
			Gallery_1_Fantastic_World: {
				/**
				 * 幻想的な世界 – 渡邉麻美の作品
				 */
				title: () => LocalizedString
				/**
				 * 「幻想的な世界」は、渡邉麻美による想像力豊かで夢のようなイラストを集めたギャラリーです。神話的な要素や宇宙的視点、遊び心あるシュールな表現が、物語性あふれる世界を描き出します。
				 */
				description: () => LocalizedString
			}
			Gallery_2_Nature_Inner_World: {
				/**
				 * 自然と内なる世界 – 渡邉麻美の作品
				 */
				title: () => LocalizedString
				/**
				 * 「自然と内なる世界」では、自然のモチーフと心の象徴を組み合わせた渡邉麻美の作品をご紹介します。動物、民話、内省的な情景が、記憶や想像、心の風景を優しく描き出します。
				 */
				description: () => LocalizedString
			}
			POP_Illustrations: {
				/**
				 * ポップイラスト – 渡邉麻美の作品
				 */
				title: () => LocalizedString
				/**
				 * 「ポップイラスト」は、色彩豊かでキャラクター性あふれる作品を集めたギャラリーです。遊び心とユーモアに満ちたイラストが、日常の喜びや想像の世界を軽やかに表現します。
				 */
				description: () => LocalizedString
			}
			Nigaoe_Works: {
				/**
				 * 似顔絵ワークス – 渡邉麻美のイラスト
				 */
				title: () => LocalizedString
				/**
				 * 「似顔絵ワークス」は、渡邉麻美によるパーソナルな似顔絵作品のコレクションです。家族の肖像、ベイビーポスター、記念日のイラストなど、大切な瞬間や絆を温かく描き出します。
				 */
				description: () => LocalizedString
			}
			Others: {
				/**
				 * その他の作品 – 渡邉麻美のイラスト
				 */
				title: () => LocalizedString
				/**
				 * 「その他の作品」は、渡邉麻美による小品や表現豊かなイラストを集めたギャラリーです。シンプルで象徴的、そして心に寄り添う作品をご覧いただけます。
				 */
				description: () => LocalizedString
			}
		}
	}
	works: {
		Gallery_1_Fantastic_World: {
			/**
			 * ギャラリー1：<br>幻想的な世界
			 */
			title: () => LocalizedString
			descriptions: {
				/**
				 * 月光花のように儚くも美しく咲く人々が集まる夜の世界
				 */
				moonFlower: () => LocalizedString
				/**
				 * 卵の中から生まれるものは何？そんな期待が入り混じる中。さあショーが始まるよ！
				 */
				theStage: () => LocalizedString
				/**
				 * 北極星から見る地球の歴史はきっとまだ短いのだろう
				 */
				polaris: () => LocalizedString
				/**
				 * 星のベッドに横たわりゆっくりとした時間を楽しむ兄妹ライオン
				 */
				relaxingTime: () => LocalizedString
				/**
				 * お揃いのバッジをつけた熱狂的ファン達は氷を溶かすくらいの盛り上がりです！
				 */
				passionateAudience: () => LocalizedString
				/**
				 * 現代社会に吹き荒れる風は風神と雷神がもたらすパワーなのかもしれないという発想から生み出されたイラスト
				 */
				fujinLajin: () => LocalizedString
				/**
				 * 辰年をイメージしたお正月のお祝いカード
				 */
				newYear: () => LocalizedString
			}
		}
		Gallery_2_Nature_Inner_World: {
			/**
			 * ギャラリー2：<br>自然と内なる世界
			 */
			title: () => LocalizedString
			descriptions: {
				/**
				 * 白熊の毛は白く見えるけど、かき氷の氷と同じく透明です
				 */
				fluffyShavedIce: () => LocalizedString
				/**
				 * 深海はきっと見えない色や形に溢れている世界
				 */
				deepInTheSea: () => LocalizedString
				/**
				 * 僕の体の80%は海からできているんだよ！
				 */
				iWannaSea: () => LocalizedString
				/**
				 * 未知の生き物は魅力的なデザインで着飾っている
				 */
				sakana: () => LocalizedString
				/**
				 * 小さな町に突然降った大雪で現れた大きな雪だるま
				 */
				busStop: () => LocalizedString
				/**
				 * ウサギの家族がおにぎりを持ってピクニックに出かけたよ
				 */
				picnic: () => LocalizedString
				/**
				 * 私は観賞用です。食べられません。
				 */
				nishikigoi: () => LocalizedString
				/**
				 * おばあちゃんの部屋には面白いものがたくさんあって飽きないな
				 */
				playStaringContest: () => LocalizedString
				/**
				 * 目指すは場所はウサギのいる月
				 */
				tripAdventure: () => LocalizedString
				/**
				 * かぐや姫の住む世界
				 */
				princessKaguya: () => LocalizedString
				/**
				 * 笑顔弾ける夏祭りへようこそ
				 */
				maturi: () => LocalizedString
				/**
				 * 「ありがとう」の気持ちをマトリョーシカに込めて
				 */
				arigatou: () => LocalizedString
				/**
				 * 他人は自分を写す鏡のようなもの
				 */
				hearts: () => LocalizedString
				/**
				 * 希望と不安をバルーンに込めて飛び立つ決心をした少女
				 */
				theFirstLightDawn: () => LocalizedString
			}
		}
		POP_Illustrations: {
			/**
			 * ポップイラスト
			 */
			title: () => LocalizedString
			descriptions: {
				/**
				 * 空飛ぶ宇宙クジラ１
				 */
				wheel: () => LocalizedString
				/**
				 * 空飛ぶ宇宙クジラ２
				 */
				wheel2: () => LocalizedString
				/**
				 * 古典模様を取り入れ、古さと新しさを交えた惑星のイラスト
				 */
				planets: () => LocalizedString
				/**
				 * カラフルなテントの中で魅惑的なパフォーマンスに夢中
				 */
				circus: () => LocalizedString
				/**
				 * 愛する人達への想いをキラキラのツリーの飾りに込めて
				 */
				bigTree: () => LocalizedString
				/**
				 * 楽しい音楽と共に特別な舟で旅をしよう！
				 */
				boat: () => LocalizedString
				/**
				 * 大きなヨーヨーはまるで生き物みたいにバウンドするから大変だ
				 */
				twins: () => LocalizedString
				/**
				 * 大根役者は実はいい味出してる愛されキャラクター
				 */
				funnyGuy: () => LocalizedString
				/**
				 * 3人の魔女はお洒落をしてお出かけの準備中
				 */
				pumpinkHouse: () => LocalizedString
				/**
				 * 立派なレンコンの車輪がついたお城は彼女のお気に入り
				 */
				lotusRootCastle: () => LocalizedString
				/**
				 * 話を聞くよと近寄ってくる可愛らしいお友達
				 */
				threeHares: () => LocalizedString
				/**
				 * 彼の帽子はカラフルで、雨にも負けない大人気の帽子です
				 */
				lovelyHat: () => LocalizedString
				/**
				 * 動物達の生き生きとした姿は自然の中でしか見ることはできない
				 */
				zoo: () => LocalizedString
				/**
				 * 大好きなどんぐりに囲まれてしあわせなリス
				 */
				nutsToYou: () => LocalizedString
				/**
				 * 陣取り合戦していたらタワーになってしまった猫の兄弟
				 */
				kittyTower: () => LocalizedString
				/**
				 * 今夜はチーズパーティーを開催します
				 */
				letsStartTheParty: () => LocalizedString
				/**
				 * 夜空に浮かぶ星たちはまるでサメのように素早く移動している
				 */
				swimming: () => LocalizedString
				/**
				 * 可愛らしいランタン達はどんどん上昇し雲の上までたどり着きました
				 */
				animalsLantern: () => LocalizedString
				/**
				 * お餅のようなみため彼らはお汁粉のお風呂で溶けてしまいそう
				 */
				oshiruko: () => LocalizedString
			}
		}
		Nigaoe_Works: {
			/**
			 * 似顔絵ワークス
			 */
			title: () => LocalizedString
			descriptions: {
				/**
				 * 日本の伝統的な吉報模様を背景に家族の幸せを願い描きました
				 */
				family1: () => LocalizedString
				/**
				 * 結婚記念日に奥様からのサプライズ似顔絵
				 */
				family2: () => LocalizedString
				/**
				 * 大切な家族を迎えられた記念にペットの名前「さくら」を背景に描いています
				 */
				pet: () => LocalizedString
				/**
				 * 女の子の誕生日メッセージ付きベイビーポスター
				 */
				baby1: () => LocalizedString
				/**
				 * 男の子の誕生日メッセージ付きベイビーポスター
				 */
				baby2: () => LocalizedString
				/**
				 * 女の子のメッセージ付き似顔絵
				 */
				girl: () => LocalizedString
				/**
				 * 男の子のメッセージ付き似顔絵
				 */
				boy: () => LocalizedString
			}
		}
		Others: {
			/**
			 * その他の作品
			 */
			title: () => LocalizedString
			descriptions: {
				/**
				 * 女の子
				 */
				girl: () => LocalizedString
				/**
				 * 年賀状
				 */
				newYearCard: () => LocalizedString
				/**
				 * 笑顔
				 */
				smile: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
