name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  deployments: write

jobs:
  early-bailout:
    runs-on: ubuntu-latest
    steps:
      - name: Create test directory
        run: |
          mkdir dist
          echo "Early bailout OK" > dist/index.html

      - name: Test deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: asamiwatanabe-portfolio
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  build-and-deploy:
    needs: early-bailout
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Update Language Files
        run: pnpx typesafe-i18n --no-watch

      - name: Build Astro
        run: pnpm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: asamiwatanabe-portfolio
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
